{% set name = "topometry" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/topometry-{{ version }}.tar.gz
  sha256: 5bb09958ba4d79078be3c6816070e60b2963ea1245537aabe3400f591c5ea4e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-learn
    - matplotlib-base
    - pandas
    - numba
    - setuptools

test:
  imports:
    - topo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davisidarta/topometry
  summary: A comprehensive dimensional reduction framework to recover latent information from data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfansler
