{% set name = "topometry" %}
{% set version = "0.2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/topometry-{{ version }}.tar.gz
  sha256: 2749f0aeaf595d8b372f591ad2327c276fdac67f0ffecad4945b0e39e90895af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-learn
    - matplotlib-base
    - pandas
    - numba
    - setuptools

test:
  imports:
    - topo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davisidarta/topometry
  summary: A comprehensive dimensional reduction framework to recover latent information from data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davisidarta
    - mfansler
